module.exports = {
    uri: {
        //AI
        GET_AI : '/ai/get/{int:ai_id}/{string:token}',
        DELETE_AI : '/ai/delete',
        GET_FARMERS_AIS : '/ai/get-farmer-ais/{string:token}',
        NEW_AI : '/ai/new',
        RENAME_AI : '/ai/rename',
        SAVE_AI : '/ai/save',
        TEST_AI : '/ai/test',
        //CHANGELOG
        GET_CHANGELOG : '/changelog/get/{string:lang}',
        LAST_CHANGELOG : '/changelog/get-last/{string:lang}',
        //CHIP
        GET_ALL_CHIP : '/chip/get-all',
        GET_TEMPLATES_CHIP : '/chip/get-templates',
        //CONSTANT
        GET_ALL_CONSTANT : '/constant/get-all',
        //COUNTRY
        GET_COUNTRY : '/country/get-all',
        //FARMER
        ACTIVATE_FARMER : '/farmer/activate',
        CHANGE_COUNTRY_FARMER : '/farmer/change-country',
        CHANGE_PASSWORD_FARMER : '/farmer/change-password',
        DISCONNECT_FARMER : '/farmer/disconnect',
        GET_FARMER : '/farmer/get/{int:id}',
        GET_CONNECTED_FARMER : '/farmer/get-connected',
        GET_FROM_TOKEN : '/farmer/get-from-token/{string:token}',
        GET_FARMER_TOKEN : '/farmer/login-token',
        REGISTER_FARMER : '/farmer/register',
        REGISTER_TOURNAMENT : '/farmer/register-tournament',
        SET_AVATAR_FARMER : '/farmer/set-avatar',
        UNREGISTER_FARMER : '/farmer/unregister',
        UNREGISTER_TOURNAMENT : '/farmer/unregister-tournament',
        UPDATE_FARMER : '/farmer/update',
        //FIGHT
        COMMENT_FIGHT : '/fight/comment',
        GET_FIGHT : '/fight/get/{int:fight_id}',
        GET_FIGHT_LOGS : '/fight/get-logs/{int:fight_id}/{string:token}',
        //FUNCTION
        GET_ALL_FUNCTIONS : '/function/get-all',
        GET_FUNCTION_CATEGORIES : '/function/get-categories',
        //GARDEN
        GET_GARDEN : '/garden/get/{string:token}',
        GET_SOLO_CHALLENGE : '/garden/get-solo-challenge/{int:leek_id}/{string:token}',
        START_FAMER_CHALLENGE: '/garden/start-farmer-challenge',
        START_FARMER_FIGHT: '/garden/start-farmer-fight',
        START_SOLO_CHALLENGE: '/garden/start-solo-challenge',
        START_SOLO_FIGTH: '/garden/start-solo-fight',
        START_TEAM_FIGHT: '/garden/start-team-fight',
        //HAT
        GET_ALL_HAT: '/hat/get-all',
        GET_TEMPLATES_HAT: '/hat/get-templates',
        //LEEK
        LEEK_ADD_CHIP: '/leek/add-chip',
        LEEK_ADD_WEAPON: '/leek/add-weapon',
        LEEK_CREATE: '/leek/create',
        LEEK_DELETE_REGISTER: '/leek/delete-register',
        GET_LEEK: '/leek/get/{int:leek_id}',
        COUNT_LEEK: '/leek/get-count',
        LEEK_GET_IMAGE: '/leek/get-image/{int:leek_id}/{int:scale}',
        LEEK_GET_LEVEL_POPUP: '/leek/get-level-popup/{int:leek_id}/{string:token}',
        LEEK_GET_NEXT_PRICE: '/leek/get-next-price/{string:token}',
        LEEK_GET_PRIVATE: '/leek/get-private/{int:leek_id}/{string:token}',
        LEEK_GET_REGISTERS: '/leek/get-registers/{int:leek_id}/{string:token}',
        LEEK_REGISTER_TOURNAMENT: '/leek/register-tournament',
        LEEK_REMOVE_AI: '/leek/remove-ai',
        LEEK_REMOVE_CHIP: '/leek/remove-chip',
        LEEK_REMOVE_HAT: '/leek/remove-hat',
        LEEK_REMOVE_WEAPON: '/leek/remove-weapon',
        LEEK_RENAME_CRYSTALS: '/leek/rename-crystals',
        LEEK_RENAME_HABS: '/leek/rename-habs',
        LEEK_SET_AI: '/leek/set-ai',
        LEEK_SET_HAT: '/leek/set-hat',
        LEEK_SET_IN_GARDEN: '/leek/set-in-garden',
        LEEK_SET_POPUP_LEVEL_SEEN: '/leek/set-popup-level-seen',
        LEEK_SET_REGISTER: '/leek/set-register',
        LEEK_SPEND_CAPITAL: '/leek/spend-capital',
        LEEK_UNREGISTER_TOURNAMENT: '/leek/unregister-tournament',
        LEEK_USE_POTION: '/leek/use-potion',
        //MARKET
        BUY_CRYSTALS: '/market/buy-crystals',
        BUY_HABS: '/market/buy-habs',
        GET_ITEM_TEMPLATES: '/market/get-item-templates/{string:token}',
        SELL_HABS: '/market/sell-habs',
        //MESSAGE
        CREATE_CONVERSATION: '/message/create-conversation',
        GET_LATEST_CONVERSATIONS: '/message/get-latest-conversations/{int:count}/{string:token}',
        GET_MESSAGES: '/message/get-messages/{int:conversation_id}/{int:count}/{int:page}/{string:token}',
        QUIT_CONVERSATION: '/message/quit-conversation',
        SEND_MESSAGE: '/message/send-message',
        //NOTIFICATIONS
        GET_LATEST_NOTIFICATIONS: '/notification/get-latest/{int:count}/{string:token}',
        READ_ALL_NOTIFICATIONS: '/notification/read-all',
        //POTION
        GET_ALL_POTIONS: '/potion/get-all',
        //RANKING
        RANKING_FUN: '/ranking/fun/{string:token}',
        GET_RANKING: '/ranking/get/{string:category}/{string:order}/{int:page}',
        GET_FARMER_RANK: '/ranking/get-farmer-rank/{int:farmer_id}/{string:order}',
        GET_HOME_RANKING: '/ranking/get-home-ranking',
        GET_LEEK_RANK: '/ranking/get-leek-rank/{int:leek_id}/{string:order}',
        GET_TEAM_RANK: '/ranking/get-team-rank/{int:team_id}/{string:order}',
        SEARCH_RANK: '/ranking/search',
        //SERVICE
        SERVICE_GET_ALL: '/service/get-all/{string:token}',
        //SUMMON
        SUMMON_GET_TEMPLATES: '/summon/get-templates',
        //TEAM
        TEAM_ACCEPT_CANDIDACY: '/team/accept-candidacy',
        TEAM_BAN: '/team/ban',
        TEAM_CANCEL_CANDIDACY: '/team/cancel-candidacy',
        TEAM_CANCEL_CANDIDACY_FOR_TEAM: '/team/cancel-candidacy-for-team',
        TEAM_CHANGE_DESCRIPTION: '/team/change-description',
        TEAM_CHANGE_MEMBER_GRADE: '/team/change-member-grade',
        TEAM_CHANGE_OWNER: '/team/change-owner',
        TEAM_CREATE: '/team/create',
        TEAM_CREATE_COMPOSITION: '/team/create-composition',
        TEAM_DELETE_COMPOSITION: '/team/delete-composition',
        TEAM_DISSOLVE: '/team/dissolve',
        TEAM_GET: '/team/get/{int:team_id}',
        TEAM_GET_CONNECTED: '/team/get-connected/{int:team_id}/{string:token}',
        TEAM_GET_PRIVATE: '/team/get-private/{int:team_id}/{string:token}',
        TEAM_MOVE_LEEK: '/team/move-leek',
        TEAM_QUIT: '/team/quit',
        TEAM_REGISTER_TOURNAMENT: '/team/register-tournament',
        TEAM_REJECT_CANDIDACY: '/team/reject-candidacy',
        TEAM_SEND_CANDIDACY: '/team/send-candidacy',
        TEAM_SET_EMBLEM: '/team/set-emblem',
        TEAM_SET_OPENED: '/team/set-opened',
        TEAM_UNREGISTER_TOURNAMENT: '/team/unregister-tournament',
        //TOKEN
        TOKEN_CHECK: '/token/check',
        //TOURNAMENT
        TOURNAMENT_COMMENT: '/tournament/comment',
        TOURNAMENT_GET: '/tournament/get/{int:tournament_id}/{string:token}',
        //TROPHY
        TROPHY_GET_ADMIN: '/trophy/get-admin/{string:lang}/{string:token}/{string:supertoken}',
        TROPHY_GET_ALL: '/trophy/get-all',
        TROPHY_GET_CATEGORIES: '/trophy/get-categories',
        TROPHY_GET_FARMER_TROPHIES: '/trophy/get-farmer-trophies/{int:farmer_id}/{string:lang}/{string:token}',
        TROPHY_UNLOCK: '/trophy/unlock/{int:trophy_id}/{string:token}',
        //WEAPON
        WEAPON_GET_ALL: '/weapon/get-all',
        WEAPON_GET_TEMPLATES: '/weapon/get-templates'
    }
}
